# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20171202_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='my_date_field',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
