# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurantlocation_my_date_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='my_date_field',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
