# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_auto_20171202_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantlocation',
            old_name='lacation',
            new_name='location',
        ),
    ]
