# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_remove_restaurantlocation_my_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
